<a href="https://colab.research.google.com/github/DharavathSuman/aiml-lab/blob/main/Assignmentp_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("HEllo")

HEllo


In [ ]:
print("aIML")


aIML


In [ ]:
##Implement basic data structure using numpy and pandas
##1.list operations
list=["apple","bananas","oranges","guava"]
print(list)
print(list[0])
print(list[3])
list.append("pineapple")
print(list)
list.insert(2,"grapes")
print(list)
list.extend(["chennai","goa","kolkata"])
print(list)
myList = [1, 2, 3, 4, 5, 6,
        7, 8, 9, 10, 11, 12]
myList.remove(6)
print("\nList after Removal of one element: ")
print(myList)
print(list)
list.pop(2)
print(list)
List1 = ['G', 'E', 'E', 'K', 'f', 'F',
        'j', 'R', 'k', 'E', 'f', 'K', 'S']
print("Initial List: ")
print(List1)
Sliced_List = List1[3:8]
print("\nSlicing elements in a range 3-8: ")
print(Sliced_List)






['apple', 'bananas', 'oranges', 'guava']
apple
guava
['apple', 'bananas', 'oranges', 'guava', 'pineapple']
['apple', 'bananas', 'grapes', 'oranges', 'guava', 'pineapple']
['apple', 'bananas', 'grapes', 'oranges', 'guava', 'pineapple', 'chennai', 'goa', 'kolkata']

List after Removal of one element: 
[1, 2, 3, 4, 5, 7, 8, 9, 10, 11, 12]
['apple', 'bananas', 'grapes', 'oranges', 'guava', 'pineapple', 'chennai', 'goa', 'kolkata']
['apple', 'bananas', 'oranges', 'guava', 'pineapple', 'chennai', 'goa', 'kolkata']
Initial List: 
['G', 'E', 'E', 'K', 'f', 'F', 'j', 'R', 'k', 'E', 'f', 'K', 'S']

Slicing elements in a range 3-8: 
['K', 'f', 'F', 'j', 'R']


In [ ]:
##Array operations
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))
arr = np.array(42)
print(arr)
#1D array
arr = np.array([1, 2, 3, 4, 5])
print(arr)
#2D array
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
#3D array
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)
arr = np.array([1, 2, 3, 4])
print(arr[0])
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[1, -1])
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42
print(arr)
print(x)
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42
print(arr)
print(x)
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
y = arr.view()
print(x.base)
print(y.base)
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 0)
print(x)
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])
# Performing addition using arithmetic operator
add_ans = a+b
print(add_ans)
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])
# Performing subtraction using arithmetic operator
sub_ans = a-b
print(sub_ans)
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])
# Performing multiplication using arithmetic operator
mul_ans = a*b
print(mul_ans)
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])
# Performing division using arithmetic operators
div_ans = a/b
print(div_ans)
mod_ans = np.mod(a, b)
print(mod_ans)
#Performing remainder on two matrices
rem_ans=np.remainder(a,b)
print(rem_ans)
# Performing power of two matrices
pow_ans = np.power(a, b)
print(pow_ans)
s=np.sin(a)
print(s)
s=np.log(a)
print(s)
s=np.log2(a)
print(s)
s=np.exp(a)
print(s)


[1 2 3 4 5]
<class 'numpy.ndarray'>
42
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
1
Last element from 2nd dim:  10
[2 3 4 5]
[42  2  3  4  5]
[1 2 3 4 5]
[42  2  3  4  5]
[42  2  3  4  5]
None
[1 2 3 4 5]
(2, 4)
(array([1, 3, 5, 7]),)
[0 1 2 3]
[  7  77  23 130]
[ 3 67  3 70]
[  10  360  130 3000]
[ 2.5        14.4         1.3         3.33333333]
[ 1  2  3 10]
[ 1  2  3 10]
[                 25          1934917632        137858491849
 1152921504606846976]
[-0.95892427  0.25382336  0.42016704 -0.50636564]
[1.60943791 4.27666612 2.56494936 4.60517019]
[2.32192809 6.169925   3.70043972 6.64385619]
[1.48413159e+02 1.85867175e+31 4.42413392e+05 2.68811714e+43]
